-- AUTOGENERATED from CV-EXT.json for the finite fixture-anchored
-- CORE_EXT parse/dispatch replay lane.
-- This vector mirror is intentionally narrower than the live runtime surface:
-- it captures only the fields needed by D2 replay. Full live verify/binding
-- closure remains separate D3/D4 work.

import RubinFormal.CoreExtRefinement

namespace RubinFormal.Conformance

open RubinFormal.CoreExtRefinement

structure CVExtVector where
  id : String
  family : String
  op : String
  covenantDataHex : String
  profiles : List ReplayProfile
  height : Option Nat
  suiteId : Option Nat
  expectOk : Bool
  expectErr : Option String
deriving Repr, DecidableEq

def cvExtVectors : List CVExtVector := [
  { id := "CV-EXT-ENV-01", family := "ENV", op := "ext_envelope_parse", covenantDataHex := "0x001000", profiles := [], height := none, suiteId := none, expectOk := true, expectErr := none },
  { id := "CV-EXT-ENV-02", family := "ENV", op := "ext_envelope_parse", covenantDataHex := "0x01", profiles := [], height := none, suiteId := none, expectOk := false, expectErr := some "TX_ERR_COVENANT_TYPE_INVALID" },
  { id := "CV-EXT-ENV-03", family := "ENV", op := "ext_envelope_parse", covenantDataHex := "0x001003010203", profiles := [], height := none, suiteId := none, expectOk := true, expectErr := none },
  { id := "CV-EXT-ENV-04", family := "ENV", op := "ext_envelope_parse", covenantDataHex := "0x0010050102", profiles := [], height := none, suiteId := none, expectOk := false, expectErr := some "TX_ERR_COVENANT_TYPE_INVALID" },
  { id := "CV-EXT-ACT-01", family := "ACT", op := "ext_activation_check", covenantDataHex := "0x001000", profiles := [{ extId := 4096, activationHeight := 50, allowedSuiteIds := [1, 3], binding := "verify_sig_ext_openssl_digest32_v1" }], height := some 49, suiteId := none, expectOk := true, expectErr := none },
  { id := "CV-EXT-ACT-02", family := "ACT", op := "ext_activation_check", covenantDataHex := "0x00100101", profiles := [{ extId := 4096, activationHeight := 50, allowedSuiteIds := [1, 3], binding := "verify_sig_ext_openssl_digest32_v1" }], height := some 50, suiteId := some 1, expectOk := true, expectErr := none },
  { id := "CV-EXT-ACT-03", family := "ACT", op := "ext_activation_check", covenantDataHex := "0x002000", profiles := [{ extId := 4096, activationHeight := 50, allowedSuiteIds := [1, 3], binding := "verify_sig_ext_openssl_digest32_v1" }], height := some 100, suiteId := none, expectOk := true, expectErr := none },
  { id := "CV-EXT-PRE-01", family := "PRE", op := "ext_pre_activation_spend", covenantDataHex := "0x001000", profiles := [{ extId := 4096, activationHeight := 50, allowedSuiteIds := [1, 3], binding := "verify_sig_ext_openssl_digest32_v1" }], height := some 10, suiteId := some 0, expectOk := true, expectErr := none },
  { id := "CV-EXT-PRE-02", family := "PRE", op := "ext_pre_activation_spend", covenantDataHex := "0x00100101", profiles := [{ extId := 4096, activationHeight := 50, allowedSuiteIds := [1, 3], binding := "verify_sig_ext_openssl_digest32_v1" }], height := some 10, suiteId := some 1, expectOk := true, expectErr := none },
  { id := "CV-EXT-PRE-03", family := "PRE", op := "ext_pre_activation_spend", covenantDataHex := "0x001000", profiles := [], height := some 100, suiteId := none, expectOk := true, expectErr := none },
  { id := "CV-EXT-ENF-01", family := "ENF", op := "ext_enforcement_check", covenantDataHex := "0x00100101", profiles := [{ extId := 4096, activationHeight := 50, allowedSuiteIds := [1, 3], binding := "verify_sig_ext_openssl_digest32_v1" }], height := some 100, suiteId := some 3, expectOk := true, expectErr := none },
  { id := "CV-EXT-ENF-02", family := "ENF", op := "ext_enforcement_check", covenantDataHex := "0x00100101", profiles := [{ extId := 4096, activationHeight := 50, allowedSuiteIds := [1, 3], binding := "verify_sig_ext_openssl_digest32_v1" }], height := some 100, suiteId := some 5, expectOk := false, expectErr := some "TX_ERR_SIG_ALG_INVALID" },
  { id := "CV-EXT-ENF-03", family := "ENF", op := "ext_enforcement_check", covenantDataHex := "0x001000", profiles := [{ extId := 4096, activationHeight := 50, allowedSuiteIds := [1, 3], binding := "verify_sig_ext_openssl_digest32_v1" }], height := some 100, suiteId := some 0, expectOk := true, expectErr := none },
  { id := "CV-EXT-ENF-04", family := "ENF", op := "ext_enforcement_check", covenantDataHex := "0x00100101", profiles := [{ extId := 4096, activationHeight := 50, allowedSuiteIds := [1, 3], binding := "verify_sig_ext_openssl_digest32_v1" }], height := some 100, suiteId := some 1, expectOk := true, expectErr := none },
  { id := "CV-EXT-PAY-01", family := "PAY", op := "ext_envelope_parse", covenantDataHex := "0x001020000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f", profiles := [], height := none, suiteId := none, expectOk := true, expectErr := none },
  { id := "CV-EXT-PAY-02", family := "PAY", op := "ext_envelope_parse", covenantDataHex := "0x001000", profiles := [], height := none, suiteId := none, expectOk := true, expectErr := none },
  { id := "CV-EXT-ERR-01", family := "ERR", op := "ext_error_priority", covenantDataHex := "0x0010050102", profiles := [{ extId := 4096, activationHeight := 50, allowedSuiteIds := [1, 3], binding := "verify_sig_ext_openssl_digest32_v1" }], height := some 100, suiteId := some 5, expectOk := false, expectErr := some "TX_ERR_COVENANT_TYPE_INVALID" },
  { id := "CV-EXT-ERR-02", family := "ERR", op := "ext_error_priority", covenantDataHex := "0xff", profiles := [{ extId := 4096, activationHeight := 50, allowedSuiteIds := [1, 3], binding := "verify_sig_ext_openssl_digest32_v1" }], height := some 100, suiteId := none, expectOk := false, expectErr := some "TX_ERR_COVENANT_TYPE_INVALID" },
  { id := "CV-EXT-ERR-03", family := "ERR", op := "ext_error_priority", covenantDataHex := "0x00100101", profiles := [{ extId := 4096, activationHeight := 50, allowedSuiteIds := [1, 3], binding := "verify_sig_ext_openssl_digest32_v1" }], height := some 100, suiteId := some 99, expectOk := false, expectErr := some "TX_ERR_SIG_ALG_INVALID" },
  { id := "CV-EXT-DUP-01", family := "DUP", op := "ext_duplicate_profile", covenantDataHex := "0x070000", profiles := [{ extId := 7, activationHeight := 10, allowedSuiteIds := [1], binding := "verify_sig_ext_openssl_digest32_v1" }, { extId := 7, activationHeight := 20, allowedSuiteIds := [3], binding := "verify_sig_ext_openssl_digest32_v1" }], height := none, suiteId := none, expectOk := false, expectErr := some "TX_ERR_COVENANT_TYPE_INVALID" },
  { id := "CV-EXT-DUP-02", family := "DUP", op := "ext_duplicate_profile", covenantDataHex := "0x070000", profiles := [{ extId := 7, activationHeight := 10, allowedSuiteIds := [1], binding := "verify_sig_ext_openssl_digest32_v1" }, { extId := 8, activationHeight := 10, allowedSuiteIds := [3], binding := "verify_sig_ext_openssl_digest32_v1" }], height := none, suiteId := none, expectOk := true, expectErr := none },
  { id := "CV-EXT-GEN-01", family := "GEN", op := "ext_activation_check", covenantDataHex := "0x00100101", profiles := [{ extId := 4096, activationHeight := 0, allowedSuiteIds := [1], binding := "verify_sig_ext_openssl_digest32_v1" }], height := some 0, suiteId := some 1, expectOk := true, expectErr := none },
  { id := "CV-EXT-GEN-02", family := "GEN", op := "ext_enforcement_check", covenantDataHex := "0x00100101", profiles := [{ extId := 4096, activationHeight := 0, allowedSuiteIds := [1, 3], binding := "verify_sig_ext_openssl_digest32_v1" }], height := some 0, suiteId := some 5, expectOk := false, expectErr := some "TX_ERR_SIG_ALG_INVALID" },
  { id := "CV-EXT-PAR-01", family := "PAR", op := "ext_activation_check", covenantDataHex := "0x001000", profiles := [{ extId := 4096, activationHeight := 50, allowedSuiteIds := [1, 3], binding := "verify_sig_ext_openssl_digest32_v1" }], height := some 10, suiteId := none, expectOk := true, expectErr := none },
  { id := "CV-EXT-PAR-02", family := "PAR", op := "ext_enforcement_check", covenantDataHex := "0x00100101", profiles := [{ extId := 4096, activationHeight := 50, allowedSuiteIds := [1, 3], binding := "verify_sig_ext_openssl_digest32_v1" }], height := some 100, suiteId := some 99, expectOk := false, expectErr := some "TX_ERR_SIG_ALG_INVALID" }
]

end RubinFormal.Conformance
