-- AUTOGENERATED (manual sync): do not edit by hand without updating the source fixture.
-- Source: conformance/fixtures/CV-FORK-CHOICE.json @ rubin-protocol origin/main 7515f7ec0be94d7cdf8a3ae0a2cc9fbff1d23e9b

set_option maxHeartbeats 10000000
set_option maxRecDepth 50000

namespace RubinFormal.Conformance

structure ForkChain where
  id : String
  targets : List String
  tipHash : String

structure CVForkChoiceVector where
  id : String
  op : String
  target : Option String
  chains : List ForkChain
  expectOk : Bool
  expectWork : Option String
  expectWinner : Option String
  expectErr : Option String

def cvForkChoiceVectors : List CVForkChoiceVector := [
  { id := "CV-FC-01", op := "fork_work", target := some "0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff", chains := [], expectOk := true, expectWork := some "0x1", expectWinner := none, expectErr := none },
  { id := "CV-FC-02", op := "fork_work", target := some "0x8000000000000000000000000000000000000000000000000000000000000000", chains := [], expectOk := true, expectWork := some "0x2", expectWinner := none, expectErr := none },
  { id := "CV-FC-03", op := "fork_choice_select", target := none, chains := [{ id := "A", targets := ["0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff", "0x8000000000000000000000000000000000000000000000000000000000000000"], tipHash := "0x00112233445566778899aabbccddeeff00112233445566778899aabbccddeeff" }, { id := "B", targets := ["0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff", "0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff", "0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff"], tipHash := "0x10112233445566778899aabbccddeeff00112233445566778899aabbccddeeff" }], expectOk := true, expectWork := none, expectWinner := some "A", expectErr := none },
  { id := "CV-FC-04", op := "fork_work", target := some "0x0000000000000000000000000000000000000000000000000000000000000001", chains := [], expectOk := true, expectWork := some "0x10000000000000000000000000000000000000000000000000000000000000000", expectWinner := none, expectErr := none },
  { id := "NEG-FC-ZERO-TARGET", op := "fork_work", target := some "0x0000000000000000000000000000000000000000000000000000000000000000", chains := [], expectOk := false, expectWork := none, expectWinner := none, expectErr := some "TX_ERR_PARSE" },
  { id := "NEG-FC-BAD-TARGET-HEX", op := "fork_work", target := some "not-hex", chains := [], expectOk := false, expectWork := none, expectWinner := none, expectErr := some "bad target" },
  { id := "NEG-FC-EMPTY-CHAINS", op := "fork_choice_select", target := none, chains := [], expectOk := false, expectWork := none, expectWinner := none, expectErr := some "bad chains" },
  { id := "NEG-FC-CHAIN-NO-TARGETS", op := "fork_choice_select", target := none, chains := [{ id := "A", targets := [], tipHash := "0x00112233445566778899aabbccddeeff00112233445566778899aabbccddeeff" }], expectOk := false, expectWork := none, expectWinner := none, expectErr := some "bad chain" },
  { id := "NEG-FC-CHAIN-ZERO-TARGET-IN-LIST", op := "fork_choice_select", target := none, chains := [{ id := "A", targets := ["0x0000000000000000000000000000000000000000000000000000000000000000"], tipHash := "0x00112233445566778899aabbccddeeff00112233445566778899aabbccddeeff" }], expectOk := false, expectWork := none, expectWinner := none, expectErr := some "TX_ERR_PARSE" },
  { id := "CV-FC-EQUAL-WORK-TIE-BREAK", op := "fork_choice_select", target := none, chains := [{ id := "A", targets := ["0x8000000000000000000000000000000000000000000000000000000000000000"], tipHash := "0x0000000000000000000000000000000000000000000000000000000000000001" }, { id := "B", targets := ["0x8000000000000000000000000000000000000000000000000000000000000000"], tipHash := "0x0000000000000000000000000000000000000000000000000000000000000002" }], expectOk := true, expectWork := none, expectWinner := some "A", expectErr := none },
  { id := "CV-FC-EQUAL-WORK-TIE-BREAK-REVERSED", op := "fork_choice_select", target := none, chains := [{ id := "A", targets := ["0x8000000000000000000000000000000000000000000000000000000000000000"], tipHash := "0x0000000000000000000000000000000000000000000000000000000000000002" }, { id := "B", targets := ["0x8000000000000000000000000000000000000000000000000000000000000000"], tipHash := "0x0000000000000000000000000000000000000000000000000000000000000001" }], expectOk := true, expectWork := none, expectWinner := some "B", expectErr := none },
  { id := "NEG-FC-TARGET-OVERFLOW", op := "fork_work", target := some "0x10000000000000000000000000000000000000000000000000000000000000000", chains := [], expectOk := false, expectWork := none, expectWinner := none, expectErr := some "bad target" },
  { id := "CV-FC-HEAVIER-WINS-DISTINCT-TIPS", op := "fork_choice_select", target := none, chains := [{ id := "A", targets := ["0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff"], tipHash := "0x0000000000000000000000000000000000000000000000000000000000000001" }, { id := "B", targets := ["0x8000000000000000000000000000000000000000000000000000000000000000"], tipHash := "0x0000000000000000000000000000000000000000000000000000000000000002" }], expectOk := true, expectWork := none, expectWinner := some "B", expectErr := none },
  { id := "CV-FC-THREE-CHAIN-HEAVIEST", op := "fork_choice_select", target := none, chains := [{ id := "light", targets := ["0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff"], tipHash := "0xaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" }, { id := "heavy", targets := ["0x0100000000000000000000000000000000000000000000000000000000000000", "0x0100000000000000000000000000000000000000000000000000000000000000"], tipHash := "0xbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb" }, { id := "mid", targets := ["0x8000000000000000000000000000000000000000000000000000000000000000"], tipHash := "0xcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc" }], expectOk := true, expectWork := none, expectWinner := some "heavy", expectErr := none },
  { id := "CV-FC-SHORT-HEAVY-BEATS-LONG-LIGHT", op := "fork_choice_select", target := none, chains := [{ id := "light", targets := ["0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff", "0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff", "0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff", "0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff", "0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff", "0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff", "0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff", "0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff"], tipHash := "0xdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd" }, { id := "heavy", targets := ["0x1000000000000000000000000000000000000000000000000000000000000000"], tipHash := "0xeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee" }], expectOk := true, expectWork := none, expectWinner := some "heavy", expectErr := none },
  { id := "NEG-FC-ALL-INVALID-TARGETS", op := "fork_choice_select", target := none, chains := [{ id := "A", targets := ["0x0000000000000000000000000000000000000000000000000000000000000000"], tipHash := "0xaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" }, { id := "B", targets := ["0x0000000000000000000000000000000000000000000000000000000000000000"], tipHash := "0xbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb" }], expectOk := false, expectWork := none, expectWinner := none, expectErr := some "TX_ERR_PARSE" }
]

end RubinFormal.Conformance
